### ISSUE TITLE
[Python] FreeBSD runtime error: "Default object is null."

### ISSUE THREAD

**Issue by vbkaisetsu** [odashi/primitiv#47]
Steps to reproduce:

Install primitiv in FreeBSD 11.1 by the following commands (root):
```sh
pkg install protobuf cmake git googletest python3
python3 -m ensurepip
pip3 install numpy cython
git clone https://github.com/odashi/primitiv.git
cd primitiv
cmake . -DPRIMITIV_BUILD_TESTS=ON
make
make test
make install
cd python-primitiv
env CPLUS_INCLUDE_PATH=/usr/local/include ./setup.py build
```
The following python code throws an error:
```python
>>> from primitiv import *
>>> dev = devices.Naive()
>>> Device.set_default(dev)
>>> g = Graph()
>>> Graph.set_default(g)
>>> dev == Device.get_default()
True
>>> g == Graph.get_default()
True
>>> node = operators.ones([2,3])               
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "primitiv/_operator.pyx", line 226, in primitiv._operator._operators.ones
    return wrapNode(op_ones[CppNode](normShape(shape).wrapped, device.wrapped[0]))
RuntimeError: /root/primitiv/primitiv/mixins.h: 69: Default object is null.
```

**Comment by odashi** [comment]
Does this problem also occurs with the same C++ implementation? Try below:

```c++
// test.cc
#include <primitiv/primitiv.h>
int main() {
  primitiv::devices::Naive dev;
  primitiv::Device::set_default(dev);
  primitiv::Graph g;
  primitiv::Graph::set_default(g);
  auto x = primitiv::operators::ones<primitiv::Node>({2, 3});
  return 0;
}
```
and run `g++ std=c++11 test.cc -lprimitiv && ./a.out`.

**Comment by vbkaisetsu** [comment]
`g++` is not installed, so I used `clang++` instead: `clang++ -std=c++11 test.cc -lprimitiv`.
No error occurs.

I found that repository's Python 3.6.2 is built with Clang 3.8.0, but clang++ 4.0.0 is installed.
I will try to build Python 3 from a source code.

**Comment by odashi** [comment]
This issue does not occur before f1206e447f4d5e61617c2ed7ed9df3696005922f, and the cause of the issue might be a (bug?) behavior of the linker about *template static member*. We need some optional code to avoid this.

**Comment by odashi** [comment]
Particularly, the linker may not generate an instance of `DefaultSettable<T>::default_obj_` for some reason. Could you please add below code in `device.cc` and a similar one in `graph.cc` and re-compile whole library? But I have no idea whether this code can compile or not.

```c++
#if SOME_LINKER_DEPENDENT_CONDITION
namespace primitiv {
namespace mixins {

template<>
Device *DefaultSettable<Device>::default_obj_ = nullptr;

}  // namespace mixins
}  // namespace primitiv
#endif  // SOME_LINKER_DEPENDENT_CONDITION
```

**Comment by vbkaisetsu** [comment]
It works fine. I used `#if __FreeBSD__` switch.

**Comment by vbkaisetsu** [comment]
I attach output of `nm` command:
```
# Ubuntu g++ 7.2.0
$ nm ../build/primitiv/libprimitiv.so | grep default_obj_
00000000002e3548 u _ZN8primitiv6mixins15DefaultSettableINS_5GraphEE12default_obj_E
00000000002e3540 u _ZN8primitiv6mixins15DefaultSettableINS_6DeviceEE12default_obj_E

# FreeBSD clang++ 4.0.0
# nm ../primitiv/libprimitiv.so  |  grep default_obj_
0000000000303690 V _ZN8primitiv6mixins15DefaultSettableINS_5GraphEE12default_obj_E
0000000000303688 V _ZN8primitiv6mixins15DefaultSettableINS_6DeviceEE12default_obj_E
```
g++ on Ubuntu generates unique global symbol (`u`),
but clang++ on FreeBSD generates weak object (`V`) for `default_obj_` used for `{get,set}_default()` functions.

**Comment by odashi** [comment]
This looks strange. Need some reports to the distribution (or search threads about this issue)?

**Comment by odashi** [comment]
BTW, the compiler switch should describe the *meaning* of behavior. I recommend, e.g., `PRIMITIV_NEED_EXPLICIT_STATIC_MEMBERS` and this should be synthesized using `CMakeLists.txt` and `config.h.in`.

**Comment by odashi** [comment]
Is it a GCC extension? But current mix-ins work well on Clang of OSX.
https://stackoverflow.com/questions/1553854/template-static-variable

**Comment by vbkaisetsu** [comment]
According to [this page](https://sourceware.org/binutils/docs/binutils/nm.html), `unique global symbol` is a GNU extension. clang on OSX uses `D: symbol in the initialized data section` which is not a GNU extension.

**Comment by odashi** [comment]
Thanks. Could we always enable code described above w/o compiler switches? If it is natural way, we should select it by default.

**Comment by eiennohito** [comment]
Could you please check what the symbol is referred to from the **python** module. I guess that in FreeBSD you get up with two copies of the variable: first in the python binary and the second in the c++ binary.

**Comment by odashi** [comment]
It looks mysterious. 
* w/o explicit instantiation (in Clang/FreeBSD): C++ module has only weak objects and Python module defines own object? Where do the pointers in the C++ module access to?
* w/ explicit instantiation: C++ module has instances and Python module links to them?

**Comment by eiennohito** [comment]
My speculations (#2):
On other linux the linkers prefer symbols from shared libraries over the weak symbols in object files.
On FreeBSD they are treated in a same way, so when compiling a python module, the first symbol (probably from an object file) is used instead of a correct one (from the C++ .so binary).

So one more idea for debugging this: what happens if you pass a primitiv.so as a **first input argument**, before any python library object files when linking a python module.

**Comment by vbkaisetsu** [comment]
Here is a result of `nm`.
```
w/o explicit instantiation:
root@:~/primitiv # nm ./primitiv/libprimitiv.so | grep default_obj_
0000000000303690 V _ZN8primitiv6mixins15DefaultSettableINS_5GraphEE12default_obj_E
0000000000303688 V _ZN8primitiv6mixins15DefaultSettableINS_6DeviceEE12default_obj_E

root@:~/primitiv # nm ./python-primitiv/build/lib.freebsd-11.1-RELEASE-amd64-3.6/primitiv/_graph.so | grep default_obj_
000000000021d740 V _ZN8primitiv6mixins15DefaultSettableINS_5GraphEE12default_obj_E
000000000021d738 V _ZN8primitiv6mixins15DefaultSettableINS_6DeviceEE12default_obj_E

=============================
w/ explicit instantiation:
root@:~/primitiv # nm ./primitiv/libprimitiv.so | grep default_obj_
0000000000303690 B _ZN8primitiv6mixins15DefaultSettableINS_5GraphEE12default_obj_E
0000000000303688 B _ZN8primitiv6mixins15DefaultSettableINS_6DeviceEE12default_obj_E

root@:~/primitiv # nm ./python-primitiv/build/lib.freebsd-11.1-RELEASE-amd64-3.6/primitiv/_graph.so | grep default_obj_
000000000021d740 V _ZN8primitiv6mixins15DefaultSettableINS_5GraphEE12default_obj_E
000000000021d738 V _ZN8primitiv6mixins15DefaultSettableINS_6DeviceEE12default_obj_E

V: weak object
B: uninitialized data section
```

Explicit instantiation generates a normal symbol for C++ library, and weak symbol for Python library.

**Comment by odashi** [comment]
Check the pointers in terms of the 1st case. Does both `.so` generate different instances?

**Comment by odashi** [comment]
To do above, e.g., adding code to print `&default_obj_` to any functions of `DefaultSettable<T>`.

**Comment by vbkaisetsu** [comment]
@odashi Yes. Two addresses (`&default_obj_` in `_graph.so` and `&default_obj_` in `libprimitiv.so`) are different value.

**Comment by odashi** [comment]
Okay, thanks. Could you be able to check it in the 2nd case, and also other platforms?

**Comment by odashi** [comment]
And is it possible to do https://github.com/odashi/primitiv/issues/47#issuecomment-341968983? I guess it is little difficult with Cython.

**Comment by eiennohito** [comment]
I think this is actually a bug of FreeBSD toolchain/dynamic linker, but an actual fix for this should be probably somehow not to leak default_obj_ to .h files.

**Comment by odashi** [comment]
Yup, I guess so.

**Comment by vbkaisetsu** [comment]
@eiennohito 
> So one more idea for debugging this: what happens if you pass a primitiv.so as a first input argument, before any python library object files when linking a python module.

Here is the current linking command:
`c++ -shared -lpthread -L/usr/local/lib -fstack-protector build/temp.freebsd-11.1-RELEASE-amd64-3.6/primitiv/_graph.o -L/usr/local/lib -lprimitiv -lpython3.6m -o build/lib.free
bsd-11.1-RELEASE-amd64-3.6/primitiv/_graph.so`

Could you tell me the order of arguments?

**Comment by odashi** [comment]
@vbkaisetsu Place `-lprimitiv` in the first argument.

**Comment by eiennohito** [comment]
Instead of -lprimitiv could you pleas pass the full path to .so file, like:
```
c++ -shared -lpthread -L/usr/local/lib <full_path_to>/primitiv.so -fstack-protector build/temp.freebsd-11.1-RELEASE-amd64-3.6/primitiv/_graph.o -L/usr/local/lib  -lpython3.6m -o build/lib.free bsd-11.1-RELEASE-amd64-3.6/primitiv/_graph.so
```

That's actually would be a bit more robust, but the variant above may do as well.

**Comment by vbkaisetsu** [comment]
It does not affect:
```
root@:~/primitiv/python-primitiv # c++ -shared -lpthread -L/usr/local/lib /usr/lib/libprimitiv.so -fstack-protector build/temp.freebsd-11.1-RELEASE-amd64-3.6/primitiv/_graph.o -L/usr/local/lib -lpython3.6m -o build/lib.freebsd-11.1-RELEASE-amd64-3.6/primitiv/_graph.so
root@:~/primitiv/python-primitiv # nm build/lib.freebsd-11.1-RELEASE-amd64-3.6/primitiv/_graph.so | grep default_obj_
000000000021d740 V _ZN8primitiv6mixins15DefaultSettableINS_5GraphEE12default_obj_E
000000000021d738 V _ZN8primitiv6mixins15DefaultSettableINS_6DeviceEE12default_obj_E
```

**Comment by eiennohito** [comment]
One more though on the topic: building an intermediate primitiv library to be static (with -fPIC though) should work around this problem.

**Comment by odashi** [comment]
I observed that always enabling the #48 option can be compiled but does not pass C++ tests on OSX/Clang.

**Comment by vbkaisetsu** [comment]
* Build OK?

  |        | OSX | FreeBSD | Linux |
  | ---- | --------- | ------ | ---- |
  | w/o explicit | OK | OK | OK |
  | w/ explicit | OK | OK | Failed |

* Symbol type of `default_obj_`

  |              |            | OSX  | FreeBSD | Linux |
  | ------------ | ---------- | ---- | ------- | ----- |
  | w/o explicit | C++ lib    | D    | V       | u     |
  |              | Python lib | D    | V       | u     |
  |              | Address    | Same | Diff    | Same  |
  | w/ explicit  | C++ lib    | S    | B       | N/A   |
  |              | Python lib | D    | V       | N/A   |
  |              | Address    | Diff | Same    | N/A   |

**Comment by odashi** [comment]
It looks really buggy.
For now, it'd be OK for me to leave this issue with merging #48.
